### ISSUE TITLE
Publish on conda-forge

### ISSUE THREAD

**Issue by davnn** [KulikDM/pythresh#4]
Hi! Would you be interested in publishing the package on conda-forge?
Given the requirements, it should be straightforward to publish it.

**Comment by KulikDM** [comment]
Hi @davnn. Publishing PyThresh on conda-forge would indeed be a good idea! I'll try either publishing it for the current version or the upcoming one, which should hopefully be soon. Will keep this issue open and give an update on any changes.

**Comment by KulikDM** [comment]
Hi @davnn PyThresh is now officially available as a conda package from version 0.2.9 and onward.
